- type: parallax
  id: Shiptest_Default
  layers:
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_Shiptest/Parallaxes/layer1.png"
      slowness: 0.998046875
      scale: "1, 1"
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_Shiptest/Parallaxes/layer2.png"
      slowness: 0.996625
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_Shiptest/Parallaxes/layer3.png"
      slowness: 0.989375
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_Shiptest/Parallaxes/asteroids.png"
      slowness: 0.984352
  layersLQ:
    - texture:
        !type:GeneratedParallaxTextureSource
        id: ""
        configPath: "/Prototypes/Parallaxes/parallax_config.toml"
        slowness: 0.875
  layersLQUseHQ: false

# Because hyperspace and the menu need their own.
- type: parallax
  id: Shiptest_FastSpace
  layers:
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_Shiptest/Parallaxes/layer1.png"
      slowness: 0.5
      scale: "3, 3"
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_Shiptest/Parallaxes/layer2.png"
      slowness: 0.25
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_Shiptest/Parallaxes/layer3.png"
      slowness: 0.15
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_Shiptest/Parallaxes/asteroids.png"
      slowness: 0.125
  layersLQ:
    - texture:
        !type:GeneratedParallaxTextureSource
        id: ""
        configPath: "/Prototypes/Parallaxes/parallax_config.toml"
        slowness: 0.5
  layersLQUseHQ: false

