- type: parallax
  id: Ancient_Default
  layers:
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_Ancient/Parallaxes/ancient.png"
      slowness: 0.25
  layersLQ:
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_Ancient/Parallaxes/ancient.png"
      slowness: 0.25
  layersLQUseHQ: false