- type: parallax
  id: SS13
  layers:
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_Ancient/Tiles/SS13/space.png"
      slowness: 0.978046875
      scrolling: "-0.25, 0"
      scale: "1, 1"
      tiled: true
  layersLQ:
    - texture:
        !type:GeneratedParallaxTextureSource
        id: ""
        configPath: "/Prototypes/Parallaxes/parallax_config.toml"
        slowness: 0.875
      scrolling: "0, -0.475"
  layersLQUseHQ: false
