# THIS FILE IS BEING IGNORED
# TO ADD MAPS TO THIS POOL, GO TO Prototypes/_Impstation/Maps/Pools/default.yml INSTEAD
- type: gameMapPool
  id: DefaultMapPool
  maps:
  #- Amber
  #- Atlas
  #- Bagel
  - Banana
  #- Barratry
  #- Boat
  #- Box
  #- Cluster
  #- Cog
  #- Convex
  #- Core
  #- Elkridge
  #- Fland
  #- Gate
  #- Hummingbird
  #- Hash
  #- Lilboat
  - Luna
  #- Loop
  #- Marathon
  #- Meta
  #- Oasis
  - Omega
  - Packed
  #- Plasma
  - Reach
  - Saltern
  - Uoui
  #- Submarine
  #- Train
  #- Union
  #- Xeno
