- type: parallax
  id: Blank

- type: parallax
  id: Default
  layers:
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_Shiptest/Parallaxes/layer1.png"
      slowness: 0.994046875
      scale: "1, 1"
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_Shiptest/Parallaxes/layer2.png"
      slowness: 0.984625
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_Shiptest/Parallaxes/layer3.png"
      slowness: 0.98175
    #- texture:
    #    !type:ImageParallaxTextureSource
    #    path: "/Textures/_Shiptest/Parallaxes/asteroids.png"
    #  slowness: 0.984352
  layersLQ:
    - texture:
        !type:GeneratedParallaxTextureSource
        id: ""
        configPath: "/Prototypes/Parallaxes/parallax_config.toml"
        slowness: 0.875
  layersLQUseHQ: false

# Because hyperspace and the menu need their own.
- type: parallax
  id: FastSpace
  layers:
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_Shiptest/Parallaxes/layer1.png"
      slowness: 0.5
      scale: "1, 1"
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_Shiptest/Parallaxes/layer2.png"
      slowness: 0.25
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_Shiptest/Parallaxes/layer3.png"
      slowness: 0.20
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_Shiptest/Parallaxes/asteroids.png"
      slowness: 0.15
  layersLQ:
    - texture:
        !type:GeneratedParallaxTextureSource
        id: ""
        configPath: "/Prototypes/Parallaxes/parallax_config.toml"
        slowness: 0.5
  layersLQUseHQ: false

